spring:
  application:
    name: authorizations-api

aws:
  dynamodb:
    endpoint: "http://localhost:8000"
    region: "us-east-1"
    access-key: "fakeAccessKeyId"
    secret-key: "fakeSecretAccessKey"